version: 2.1
orbs:
  sectest: ci-auto-test1/ci-auto-orb1@dev:alpha10
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - attach_workspace:
        at: /tmp/workspace2
    - checkout
    - run: find .
    - run: cp apkpure_app_887.apk /tmp/workspace2/test.apk
    - sectest/sectest:
        auto_file: /tmp/workspace2/test.apk
        auto_wait: "30"
        auto_score: "50"
