version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      TERM: dumb
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: mkdir -p /tmp/workspace/nowsecure-auto-security-test
      - run: cp apkpure_app_887.apk /tmp/workspace/test.apk
      - run: env > /tmp/workspace/nowsecure-auto-security-test/env.out
      - run: find /tmp/workspace > /tmp/workspace/nowsecure-auto-security-test/find.out
      - run: find
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - nowsecure-auto-security-test/*
