version: 2.1
orbs:
  sectest: bhatti/sectest@dev
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: mkdir -p /tmp/workspace/nowsecure-auto-security-test
      - run: cp apkpure_app_887.apk /tmp/workspace/test.apk
      - sectest/sectest:
        auto_file: test.apk
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - nowsecure-auto-security-test/*
